# Generated by Django 5.0.3 on 2024-03-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_cat_finch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finch',
            new_name='Dog',
        ),
    ]
